### ISSUE TITLE
Generated link returns error 403

### ISSUE THREAD

**Issue by sukov** [alexeichhorn/YouTubeKit#16]
Most of the generated video URLs are returning 403 error when accessed. Example: https://www.youtube.com/watch?v=eVTXPUF4Oz4&ab_channel=LinkinPark

**Comment by Muhammad572** [comment]
There is some problem with this video maybe its access issue "only user can access video" other video on this channel are working fine for me.

**Comment by Frankenxtein** [comment]
I am also receiving same error @alexeichhorn. Extracted URL is not playable anymore.

**Comment by Muhammad572** [comment]
If its your own channel you have to change this videos access level to public its for youtube user onlySent from my iPhoneOn 13-Aug-2023, at 11:54 PM, Frankenxtein ***@***.***> wrote:﻿
I am also receiving same error @alexeichhorn. Extracted URL is not playable anymore.

**Comment by alexeichhorn** [comment]
Just pushed a commit to main that fixes this issue for me. Lmk if it works for you as well.
Will do a proper release in the next couple of days

**Comment by sukov** [comment]
That did not work for me, but setting `init(client: ClientType = .androidMusic`  on InnerTube fixed the issue.
