### ISSUE TITLE
QUESTION: Downloading is really slow

### ISSUE THREAD

**Issue by ldenoue** [alexeichhorn/YouTubeKit#17]
I noticed that loading the URL retrieved in a WKWebView's AUDIO element seems to load the audio instantly.
We can also skip to different times.

However, performing the download in Swift using for example the `Alamofire` library is super slow, as if the server was throttling our request.

Any idea on how we could improve the situation?

**Comment by alexeichhorn** [comment]
The way I solved it is by downloading chunks of 2-10 MB in parallel with separate requests and then combining them again. Depending on the type of stream you are downloading, there are different options to request the specific range of bytes.

**Comment by ldenoue** [comment]
Thank you!
I am only interested in an audio stream (to transcribe them).
Do you have code samples or links showing how to download in chunks?

**Comment by alexeichhorn** [comment]
Basically, you can only download a certain chunk of a file by setting the HTTP headers like this:
```swift
var request = URLRequest(url: url)
request.addValue("bytes=\(contentStart)-\(contentEnd)", forHTTPHeaderField: "Range")
```

Depends a bit on the stream type if this works without throttling or not. For dash audio I personally use this as the previous method is sometimes still throttling (no guarantees that it always works):
```swift
var components = URLComponents(url: url, resolvingAgainstBaseURL: false)!
components.queryItems?.append(URLQueryItem(name: "range", value: "\(contentStart)-\(contentEnd)"))
          
var request = URLRequest(url: components.url!)
request.httpMethod = "post"
```

**Comment by ldenoue** [comment]
Thanks a lot, I managed to make it work using range requests.
Downloading a 30 minutes audio now takes about 5 seconds with chunks of 2MB.

**Comment by yoondj98** [comment]
I tried
```
components.queryItems?.append(URLQueryItem(name: "range", value: "\(contentStart)-\(contentEnd)"))
```

this to get part of audio from youtube video.
Although, I successed for get 0:00~0:50 audio easily, I failed to get 2:00~2:50 audio.(Exactly, I got Audio Data, but it couldn;'t played with AVAudioPlayer...)

I can't understand why from 0:00 can be played, and others are impossible...

**Comment by gavin1818** [comment]
@alexeichhorn Hey Alex, thank you for creating this amazing library! It’s been incredibly helpful.

I was wondering if you could provide a more detailed code example for implementing the chunked download approach you mentioned. 

Thank you !
