### ISSUE TITLE
can't get video with audio

### ISSUE THREAD

**Issue by 666bsw** [alexeichhorn/YouTubeKit#19]
https://www.youtube.com/watch?v=NbXSj2WT6nw
https://m.youtube.com/watch?v=NbXSj2WT6nw

example address
all addresses have this problem.

I get an array of links and print

 includesVideoTrack = true ==== includesAudioTrack false format mp4
 includesVideoTrack = true ==== includesAudioTrack false format webm
 includesVideoTrack = true ==== includesAudioTrack false format mp4
 includesVideoTrack = true ==== includesAudioTrack false format webm
 includesVideoTrack = true ==== includesAudioTrack false format mp4
 includesVideoTrack = true ==== includesAudioTrack false format webm
 includesVideoTrack = true ==== includesAudioTrack false format mp4
 includesVideoTrack = true ==== includesAudioTrack false format webm
 includesVideoTrack = true ==== includesAudioTrack false format mp4
 includesVideoTrack = true ==== includesAudioTrack false format webm
 includesVideoTrack = false ==== includesAudioTrack true format mp4
 includesVideoTrack = false ==== includesAudioTrack true format mp4
 
 there are links only with video or only with audio
missing together
requests used different, no filters applied
let video = YouTube(url: videoURL)
let video = YouTube(videoID: videoID)

the problem was like this:
class InnerTube
init(client: **ClientType = .ios**, useOAuth: Bool = false, allowCache: Bool = true)

links with video and audio began to come
init(client: **ClientType = .web,** useOAuth: Bool = false, allowCache: Bool = true) { 
but very few links, only two

**Comment by alexeichhorn** [comment]
Hey, I've recently made numerous changes to the entire process. Could you please retry your code with the latest commit in the main branch? I would appreciate some feedback before releasing a new version.

**Comment by 666bsw** [comment]
Hello!
We really like your framework. We will continue to use it. We can't test it right now due to high load. We'll try to test it during the holidays.
Thank you very much.

**Comment by 666bsw** [comment]
I'm sorry
I had a lot of work.
new version works great!!!
Thank you!
best regards
