### ISSUE TITLE
RegexMatchError after breaking change from YT

### ISSUE THREAD

**Issue by dkasaj** [alexeichhorn/YouTubeKit#2]
Looks like yesterday there was a breaking change from YT. 
Pytube team have already [fixed the issue](https://github.com/pytube/pytube/issues/1199) but sadly YouTubeKit breaks on getTransformObject regex. 
I've attempted to escape the variable as hinted by the // TODO:, but it did not help.
P.S. what an amazing job you've done with this so far!

**Comment by ror1212** [comment]
Update the library with the changes you made and then later we solve the problem of the kit... We want a solution All telegram bots and Windows programs are stopped .. Update the library with what you have solved

**Comment by alexeichhorn** [comment]
This issue should be fixed with 0.1.3. 
The tests on GitHub still fail as they're still using Xcode 13.1, but they succeed locally just fine.
