### ISSUE TITLE
Over the last weeks, more and more videos can't be downloaded

### ISSUE THREAD

**Issue by jordibruin** [alexeichhorn/YouTubeKit#20]
First of all, I love this SPM package. I use it in www.macwhisper.com and it makes a lot of people happy! Over the last week, I've been receiving messages from users that they're unable to download more and more YouTube videos. Here's an example I was able to reproduce.

Would love any ideas, thanks!

I'm using these settings:
```
let stream = try await YouTube(url: URL(string: urlString)!)
                    .streams
                    .filter {
                        $0.isProgressive && $0.subtype == "mp4"
                    }
                    .lowestResolutionStream()
```

This Youtube video:
`https://youtu.be/dkpDjd2nHgo`

Gives this stream url:
`https://rr4---sn-5hnednsz.googlevideo.com/videoplayback?expire=1692295932&ei=mw7eZJTuPNC7x_APpfSyuAo&ip=109.38.145.80&id=o-AHFLv1AmaIAbbJNXCgwtS9kUlSALTqbC_TQ62NJm5nhB&itag=18&source=youtube&requiressl=yes&mh=_c&mm=31%2C29&mn=sn-5hnednsz%2Csn-5hne6ns6&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=1270000&spc=UWF9f5Q0OSv3De2zhUTox19rvDl877swgPrAjymrIQ&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=361938904&ratebypass=yes&dur=5046.926&lmt=1692258791620214&mt=1692273917&fvip=3&fexp=24007246%2C24362685&beids=24350017&c=ANDROID&txp=4438434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgDcCmFqsM46xJxUYRLEzb7kk9KkTgebmh20BlMPX_EtYCIQCYJbUggvCvlY99fZbXFMLS7VNqgJr6ZdeRECbNWlf97w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJVWcwK31jeNHq5HYDZjzjvTve_r6d_1xJ-FezBcAiH0AiAmPZXaCruRM65mpADZtZnY4iiTMSz0Ud4L5Vs4Emd2MQ%3D%3D`

When I open that link in Brave I get this error:
<img width="669" alt="image" src="https://github.com/alexeichhorn/YouTubeKit/assets/170948/df98a7ab-8aa4-44f4-9de1-df939182396d">

**Comment by xzenon** [comment]
I'm experiencing the same issue over the last days. Is it possible to fix somehow or problem is mostly on the YouTube side?

**Comment by alexeichhorn** [comment]
Unfortunately, I can't reproduce it, even with the video you sent. It works for me. I assume the outcome of this is highly dependent on geolocation. But I will try to investigate it using different VPNs in the next couple of days.

**Comment by jordibruin** [comment]
Appreciate it @alexeichhorn , I'm also investigating more and will update here if I discover anything!

**Comment by jordibruin** [comment]
@alexeichhorn I'm curious to know if you have a sample app you used to test? And if so, if I could have a look at it 🙂

**Comment by alexeichhorn** [comment]
I don't use any testing app. Instead, I mostly use unit tests to test the extractions - breakpoints and everything work just fine with that.

**Comment by alexeichhorn** [comment]
@jordibruin I still cannot reproduce this exact issue - I only get it on the older version (`0.1.8`). However, I found that in many countries this type of stream (`$0.isProgressive && $0.subtype == "mp4"`) isn't even available. 

But maybe check out the branch `fix/issue-20`, I tried some stuff there with automatically changing the innertube client on failure. Could maybe help in some cases and also allows me to prefer the `iosMusic` client type which does not support all video types (obviously), but generally returns better streams in my and others' experiences.

**Comment by Oficerov** [comment]
Same error just with big videos, on 40-60% downloading. Short videos working good.

**Comment by IAMTHEBURT** [comment]
> Same error just with big videos, on 40-60% downloading. Short videos working good.
> 
> UPD: decide this problem by manipulating client name in innertube

Hello,
Could you please explain what does it mean "manipulating client name in innertube"?
Thanks

**Comment by IAMTHEBURT** [comment]
Found in InnerTube.swift

init(client: ClientType = .ios, useOAuth: Bool = false, allowCache: Bool = true)

replacement with an other client helps a bit

init(client: ClientType = .web, useOAuth: Bool = false, allowCache: Bool = true)
