### ISSUE TITLE
Audio stream duration doubled?

### ISSUE THREAD

**Issue by hliang** [alexeichhorn/YouTubeKit#21]
I'm using YouTubeKit to get the audio url. and feed it to AVPlayer. It plays fine, except audio's total length seems doubled.

For a 1-minute video, we can get an audio url, but the total duration of the stream is 2 minutes. After playing 1 minute, the player keeps playing for another 1 minute, but there is no sound. I try copying the audio url and paste it in browser to play, also showing double audio length.

Has anyone seen this issue before?

Not sure if this is YouTubeKit specific or YouTube making it that way.

**Comment by alexeichhorn** [comment]
Yes, some audio streams have this issue, but it's not something I can fix without actually downloading the audio and trimming it to the correct length. For my own project, I have been using the duration from YouTube's API to display it to the user.

**Comment by hliang** [comment]
We probably also need a workaround like that.
Thanks for the info!
