### ISSUE TITLE
Can't play video (iOS17.1.1)

### ISSUE THREAD

**Issue by sycode** [alexeichhorn/YouTubeKit#30]
Hello.
An issue occurred where the video URL could not be obtained on iOS17.1.1.

https://www.youtube.com/watch?v=XzOvgu3GPwY

```swift
let stream = try await YouTube(videoID: "XzOvgu3GPwY").streams
    .filter { $0.isProgressive && $0.subtype == "mp4" && $0.includesVideoTrack }
    .highestResolutionStream()
``` 
=> return nil

I edited the code as below, but only the video plays, the audio does not work.
```swift
let stream = try await YouTube(videoID: "XzOvgu3GPwY").streams
    .filter { $0.subtype == "mp4" }
    .highestResolutionStream()
``` 

Could you tell me if there is a way to improve it?

**Comment by waliid** [comment]
Hello @sycode,

Could you please try this:

```swift 
try await YouTube(videoID: videoId).streams
                        .filter { $0.subtype == "mp4" && $0.includesVideoTrack }
                        .highestAudioBitrateStream()
```

Thanks,

**Comment by sycode** [comment]
thank you for your reply.

I tried it and the video played but there was no audio.
Next, I tried changing it as below, but this time the audio played, but there was no video.

```swift
try await self.streams
                .filter { $0.subtype == "mp4" && $0.includesAudioTrack }
                .highestAudioBitrateStream()?
``` 

Have YouTube specifications changed?
When I tried playing it with iOS AVPlayer, the audio length was twice the normal length and the operation became strange.
It may be a Core Audio bug in iOS17.1.1.

**Comment by waliid** [comment]
It's really weird because I've tried using your ID and the bunch of code I provided, and I can hear the audio, I'm also using `AVPlayer`. Is your repository public?

**Comment by AdnanAliShabir** [comment]
```
try await self.streams
                .filter { $0.subtype == "mp4" && $0.includesAudioTrack }
                .highestAudioBitrateStream()?
```
                
If use this then only audio and no video. 

Thanks

**Comment by AdnanAliShabir** [comment]
It works if change the  

class InnerTube
`init(client: ClientType = .ios, useOAuth: Bool = false, allowCache: Bool = true)`

with

`init(client: ClientType = .web, useOAuth: Bool = false, allowCache: Bool = true)`

**Comment by lk568999** [comment]
Hello @waliid @AdnanAliShabir @sycode

**Comment by alexeichhorn** [comment]
Hey, I've recently made numerous changes to the entire process. Could you please retry your code with the latest commit in the main branch? I would appreciate some feedback before releasing a new version.

**Comment by lk568999** [comment]
I am very happy to try it. If there are any new questions, I will ask again. Thank you for your guidance.

**Comment by lk568999** [comment]
I'm glad that the new update has solved my problem. Thank you for your update, and we look forward to the launch of the remote server feature.

**Comment by sycode** [comment]
@AdnanAliShabir 
When I updated to the latest commit, the video was successfully played with audio!
thank you very much!

**Comment by AdnanAliShabir** [comment]
@sycode 
Sounds good.
