### ISSUE TITLE
alert "content is not available on this app."

### ISSUE THREAD

**Issue by hileo** [alexeichhorn/YouTubeKit#37]
Hello, it doesn't seem to be working properly now with this message
“The following content is not available on this app. Watch this content on the latest version of YouTube”

![IMG_5218](https://github.com/alexeichhorn/YouTubeKit/assets/3161628/267a87ba-82e9-4927-b50d-caf9773f120f)

What can I do to solve this problem?

**Comment by sycode** [comment]
Same problem.

**Comment by sycode** [comment]
It seems that the problem was occurring with other libraries as well.
https://github.com/anxdpanic/plugin.video.youtube/issues/663

**Comment by alexeichhorn** [comment]
Could replicate it with some quite new videos. Have a fix in mind and will implement it in the coming days. Thanks guys

**Comment by alexeichhorn** [comment]
@hileo @sycode It should be fixed in the main branch. Can you maybe test it with your videos and report back?

**Comment by sycode** [comment]
> @hileo @sycode It should be fixed in the main branch. Can you maybe test it with your videos and report back?

That's excellent!
Played successfully.
Thank you for your support!

**Comment by manchan** [comment]
still having problems.
```
finished with error [57] Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={NSErrorFailingURLStringKey=https://youtubekit-remote.losjet.com/v1?videoID=VGKrQu3ERgY, NSErrorFailingURLKey=https://youtubekit-remote.losjet.com/v1?videoID=VGKrQu3ERgY, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalWebSocketTask <6145204D-EB9B-417D-9636-EA638D57E740>.<18>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalWebSocketTask <6145204D-EB9B-417D-9636-EA638D57E740>.<18>}
```

**Comment by hileo** [comment]
> @hileo @sycode It should be fixed in the main branch. Can you maybe test it with your videos and report back?
Succeeded.
Thank you for your support.

**Comment by hileo** [comment]
> @hileo @sycode It should be fixed in the main branch. Can you maybe test it with your videos and report back?

Succeeded.
Thank you for your support.

**Comment by alexeichhorn** [comment]
> still having problems.
> 
> ```
> finished with error [57] Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={NSErrorFailingURLStringKey=https://youtubekit-remote.losjet.com/v1?videoID=VGKrQu3ERgY, NSErrorFailingURLKey=https://youtubekit-remote.losjet.com/v1?videoID=VGKrQu3ERgY, _NSURLErrorRelatedURLSessionTaskErrorKey=(
>     "LocalWebSocketTask <6145204D-EB9B-417D-9636-EA638D57E740>.<18>"
> ), _NSURLErrorFailingURLSessionTaskErrorKey=LocalWebSocketTask <6145204D-EB9B-417D-9636-EA638D57E740>.<18>}
> ```

That's completely unrelated. See #34. If this occurs all the time, then open a separate issue

**Comment by manchan** [comment]
@alexeichhorn 
I created the issue because it is a problem that happens all the time. 
Please check it out. #40
