### ISSUE TITLE
fatal error url: Access denied

### ISSUE THREAD

**Issue by hoangnam714** [alexeichhorn/YouTubeKit#46]
<img width="666" alt="image" src="https://github.com/alexeichhorn/YouTubeKit/assets/51524705/32010f2a-7ce8-4302-b0ee-d9ed9d2e67ed">

For some videos, when I get the video url, they cannot be accessed. For some videos, it is still fine, is there any special configuration?
Video ID : v__LWzseKT4

request: 
```
let ytm = YouTube(videoID: "v__LWzseKT4", methods: [.local])
                    let streams = try await ytm.streams
                        .filter { $0.includesVideoAndAudioTrack && $0.fileExtension == .mp4  }
                        .highestResolutionStream()
```

**Comment by alexeichhorn** [comment]
Same as #44: I pushed some fixes. Can you try again with the current `main` branch.

**Comment by hoangnam714** [comment]
I tested it again and it worked, but why does it only return the 360p video resolution url and not 720p anymore?

**Comment by hoangnam714** [comment]
@alexeichhorn A new error arises: unable to get mimeType
<img width="482" alt="image" src="https://github.com/alexeichhorn/YouTubeKit/assets/51524705/b031a783-f4fe-44ed-b7ee-6119a9d374ef">

**Comment by alexeichhorn** [comment]
I guess you are using `.remote` method. It's expected there and I forgot to deprecate the usage of `mimeType` along with `type` and `subtype` back when introducing remote mode. My bad.

**Comment by alexeichhorn** [comment]
> I tested it again and it worked, but why does it only return the 360p video resolution url and not 720p anymore?

I also noticed that more and more videos only have low-resolution combined video-audio tracks. This is on YouTube's side unfortunately. `yt-dlp` also suffers from it.
If you want to download the video, you could download audio and video separately and combine them afterwards. Maybe include this kind of functionality in the library directly at some point in the future.
For streaming it's hard to do something except waiting and hoping 😉.

**Comment by hoangnam714** [comment]
thank you for your support, so far it's pretty good, I'll look into combining video and audio, can you suggest me a useful player for the video, too bad because AVplayer it will Download the entire video and play it instead of downloading a part first and playing it

**Comment by alexeichhorn** [comment]
So you want a player that combines video and audio on the fly?
Don't know any. Maybe VLCKit supports it somehow, but not sure.
