### ISSUE TITLE
QUESTION: How to get the middle of audio?

### ISSUE THREAD

**Issue by yoondj98** [alexeichhorn/YouTubeKit#58]
Hello, Alex.

I asked about extracting part of audio to you, and I solved that problem.
Thank You!

But, got something wrong about getting middle part of audio.

I tried
```
components.queryItems?.append(URLQueryItem(name: "range", value: "\(contentStart)-\(contentEnd)"))
```

this to get part of audio from youtube video.
Although, I successed for get 0:00~0:50 audio easily, I failed to get 2:00~2:50 audio.(Exactly, I got Audio Data, but it couldn;'t played with AVAudioPlayer...)

I can't understand why from 0:00 can be played, and others are impossible...

I always got this Error..😂😂
```
error	NSError	domain: "NSOSStatusErrorDomain" - code: 1954115647	0x000000030342d0e0
```

**Comment by alexeichhorn** [comment]
So an audio file is, very simply put, set up like this: First bytes in the file is metadata that defines the codec etc for a player to know how to play this file, after that you have actual content. So when you only retrieve data from a point that is not 0, you basically remove the metadata, which is crucial. 

Want do you want to achieve? Play the audio file from a certain position?

**Comment by yoondj98** [comment]
Yeah right! 
Getting whole of the file needs too long time to wait and request too much of LTE or 5G data usage, so I want to get it only parts of audio like 0:00~0:10, 1:00~1:10, 2:00~2:10,...
Then I will use each part to play in the App.

**Comment by yoondj98** [comment]
@alexeichhorn  Do you need anything I have to provide more information?

**Comment by alexeichhorn** [comment]
If you plug in the unmodified url straight into AVPlayer (no manual downloading) and seek directly to the desired starting position, it shouldn't load unnecessary parts of the file. Or did you try this already?

**Comment by yoondj98** [comment]
I tried that and I couldn't play it.🥲🥲

Then you mean if I need to play the part of audio File, I have to download all data of the file?

And if it's long time to download, use this code several times
```
var request = URLRequest(url: externalURL)
                    request.addValue("bytes=\(startByte)-\(endByte)", forHTTPHeaderField: "Range")
                    var (data, response) = try await URLSession.shared.data(for: request)
```
to get each part(ex)0:00~2:00, 2:00~4:00, 4:00~6:00,...) of the audio data. Then append all of the audio data for using in player??

**Comment by alexeichhorn** [comment]
How did you try it?
Works for me. I have an audio app and I'm using `AVPlayer` (might not work on `AVAudioPlayer`). See this:
```swift
let audioStream = try await YouTube(url: URL(string: "https://www.youtube.com/watch?v=xyz)!)
                .streams
                .filterAudioOnly()
                .filter { $0.isNativelyPlayable }
                .highestAudioBitrateStream()!
let playerItemAudio = AVPlayerItem(url: audioStream.url)
```

**Comment by yoondj98** [comment]
I'm so sorry to answer lately.
I could make it works with getting whole Audio file from your server.
I used a method where a single audio file is divided into 15-minute segments, fetched, and then combined for use.
