### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 666bsw** [alexeichhorn/YouTubeKit#6]
Hey!
often crash here
can i fix it somehow?
![Снимок экрана 2023-01-13 в 13 15 17](https://user-images.githubusercontent.com/78748377/212297445-1dc02251-93f0-4b5f-9fea-fb91e2fd2ad1.png)

**Comment by alexeichhorn** [comment]
Is it crashing reliably for certain videos or just randomly?
If there are videos you can often reproduce it with, can you send me their links?

**Comment by 666bsw** [comment]
used for audio
I'll try to get a link
if there is a repeat, I will send

let stream = try? await YouTube(videoID: id).streams
                .filterAudioOnly()
                .filter { $0.subtype == "mp4" }
                .highestAudioBitrateStream()

**Comment by 666bsw** [comment]
crash the same playlist,  containing these indices:
ID = 7CKtQ4-wfTM
ID = itqGVDIBkWw
ID = SibXBrOxA0o
ID = F-Y1LKxGU8I
ID = jNs6aQGCOaU
ID = M6cpB2hh5BA
ID = NvbaDuEViDg
ID = igJeBYmqK2Y
ID = qceopW0PD74
ID = MzI_CIYSsfQ
ID = EUS9tcFu1fE
ID = WgJK1-iGNco
ID = Dxw11CKI03Y
ID = vN12KY7eR8U
ID = 9EX7HR1Fsq8
ID = nM8e0LjQEvE
ID = Rs8aq-e_J4M
ID = 6jMG1BG54kQ
ID = 9S8Pw4pfrKE
ID = nFwcl-tKJdU
ID = s3x2-Qey9AM
ID = blka05VlAQw
ID = kP4EHv7iLmE
ID = Qx1LngL28C4
ID = yc8XTr4HI4o
ID = JCFeALamXRY
ID = ufvvyIxci4Y
ID = RJkVfDDMuVs
ID = eKVcpJZO6k4
ID = tWVcVDIYoGk
ID = d8e9sw6_oec
ID = 4EfM6rPmxow
ID = C3UV02D8W5A
ID = NuXdxMEbYeQ
ID = x1ZtIVuHph0
ID = XBleNfmkScA
ID = eLAHSRmFFzE
ID = jsLUXz0UOeg
ID = kmxPFKIe4Zs
ID = HnLyfoamQyM
ID = tYXQb_-8FoY
ID = UBS52IgUDZ0
ID = UBNUTdtvdbA
ID = Xh4K1syaghE
ID = mwnLxK7Ada8

I can't tell the exact index.
group operation (try await withThrowingTaskGroup)

**Comment by 666bsw** [comment]
thanks!

**Comment by alexeichhorn** [comment]
This should be fixed now with `0.1.7`. Was a super dumb typo actually, but some YouTube API changes brought that forward.
Thanks for reporting
