### ISSUE TITLE
Looks like "n-function signature" by-pass fails and needs regex updated

### ISSUE THREAD

**Issue by someziggyman** [alexeichhorn/YouTubeKit#67]
it looks like there have been changes to YT and its signatures for playback or whatever it's called. So, my guess is:  "class func getInitialFunctionName(js: String) throws -> String "  regex needs to be updated in cipher.swift class. 

Hints:
https://github.com/yt-dlp/yt-dlp/commit/4c85ccd1366c88cf93982f8350f58eed17355981
https://github.com/yt-dlp/yt-dlp/commit/a95ee6d8803fca9157adecf63732ab58bf87fd88
https://github.com/yt-dlp/yt-dlp/commit/4bd2655398aed450456197a6767639114a24eac2

I'm not a dev, just looking into the world of Swift starting my coding journey.. Have been playing with bash and terminal scripts a lot. Wanted to experiment with like a test Swift project to use youtubekit and encountered an issue with any link I tried would fail with log messages - failed to calculate n... maybe I'm doing something wrong.

**Comment by jcltravels** [comment]
Any thoughts on how to fix this?  I am hoping for a patch for this as my app is broken now :(

**Comment by alexeichhorn** [comment]
Started working on it on #68

**Comment by jcltravels** [comment]
Thank you so much Alex.  Much appreciated.

**Comment by someziggyman** [comment]
Please not there was a slight change to regex. no idea if you need to fix it here as well, but just in case https://github.com/yt-dlp/yt-dlp/commit/5460cd91891bf613a2065e2fc278d9903c37a127

**Comment by alexeichhorn** [comment]
@someziggyman yeah, I did. Thanks

**Comment by alexeichhorn** [comment]
Release is out with all the fixes
